### ISSUE TITLE
Update conda-build to 2.0.1?

### ISSUE THREAD

**Issue by PeterDSteinberg** [conda-forge/conda-forge.github.io#240]
Hi. I am getting an error in conda-build on conda-forge that I am not getting locally with conda-build in more recent versions than 1.21.14. 

The error is several parts.

 * Warns I'm on out of date conda-build version 1.21.14
 * Conda-build has no attribute "api" error:

```
...Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/conda_build_all/builder.py", line 200, in build
    conda_build.api.build(meta.meta, config=config)
AttributeError: module 'conda_build' has no attribute 'api'
```
 * In processing of that error, another error occurs: Unsatisfiable constraint on pandas 0.18.1 and numpy 1.10|1.11, which I think should be fine as a combination of packages

```
conda.resolve.Unsatisfiable: The following specifications were found to be in conflict:
  - pandas ==0.18.1 -> numpy 1.10*|1.11*
  - setuptools
```

[Full build on circle CI](https://circleci.com/gh/conda-forge/staged-recipes/9220?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) (scroll to the bottom)

[Here's the recipe I am trying to build](https://github.com/PeterDSteinberg/staged-recipes/blob/PR-to-trigger-test/recipes/OG-USA/meta.yaml)

Any ideas?  Can this be solved with upgrading conda-build?

**Comment by patricksnape** [comment]
We are in the middle of upgrading but there are some practical administrative tasks that we must complete before we can perform the upgrade.

**Comment by jakirkham** [comment]
The error referred to is with `conda-build-all` AFAICT. Going to move it over to that issue tracker to see if we can't get it sorted out. Thanks for raising @PeterDSteinberg.

**Comment by jakirkham** [comment]
This issue was moved to SciTools/conda-build-all#66
